import { TRANSACTION_STATES } from "./transactionStates.js";

/**
 * Single source of truth for allowed transaction state transitions.
 * Build Plan Section 6
 */
export const ALLOWED_TRANSITIONS = {
  [TRANSACTION_STATES.DISCOVERED]: [TRANSACTION_STATES.QUOTED, TRANSACTION_STATES.CANCELLED],
  [TRANSACTION_STATES.QUOTED]: [TRANSACTION_STATES.NEGOTIATING, TRANSACTION_STATES.AGREED, TRANSACTION_STATES.QUOTE_EXPIRED, TRANSACTION_STATES.CANCELLED],
  [TRANSACTION_STATES.NEGOTIATING]: [TRANSACTION_STATES.AGREED, TRANSACTION_STATES.POLICY_REJECTED, TRANSACTION_STATES.CANCELLED],
  [TRANSACTION_STATES.AGREED]: [TRANSACTION_STATES.RESERVED, TRANSACTION_STATES.POLICY_EVALUATED, TRANSACTION_STATES.HUMAN_APPROVAL_REQUIRED, TRANSACTION_STATES.POLICY_REJECTED, TRANSACTION_STATES.CANCELLED],
  [TRANSACTION_STATES.RESERVED]: [TRANSACTION_STATES.POLICY_EVALUATED, TRANSACTION_STATES.HUMAN_APPROVAL_REQUIRED, TRANSACTION_STATES.PAYMENT_PENDING, TRANSACTION_STATES.CANCELLED],
  [TRANSACTION_STATES.POLICY_EVALUATED]: [TRANSACTION_STATES.HUMAN_APPROVAL_REQUIRED, TRANSACTION_STATES.PAYMENT_PENDING, TRANSACTION_STATES.POLICY_REJECTED, TRANSACTION_STATES.CANCELLED],
  [TRANSACTION_STATES.HUMAN_APPROVAL_REQUIRED]: [TRANSACTION_STATES.PAYMENT_PENDING, TRANSACTION_STATES.REJECTED, TRANSACTION_STATES.CANCELLED],
  [TRANSACTION_STATES.PAYMENT_PENDING]: [TRANSACTION_STATES.PAYMENT_PROCESSING, TRANSACTION_STATES.PAYMENT_VERIFICATION, TRANSACTION_STATES.PAYMENT_FAILED, TRANSACTION_STATES.CANCELLED],
  [TRANSACTION_STATES.PAYMENT_PROCESSING]: [TRANSACTION_STATES.PAYMENT_VERIFICATION, TRANSACTION_STATES.PAID, TRANSACTION_STATES.PAYMENT_FAILED],
  [TRANSACTION_STATES.PAYMENT_VERIFICATION]: [TRANSACTION_STATES.PAID, TRANSACTION_STATES.PAYMENT_FAILED],
  [TRANSACTION_STATES.PAID]: [TRANSACTION_STATES.FULFILLMENT, TRANSACTION_STATES.COMPLETED, TRANSACTION_STATES.DISPUTED],
  [TRANSACTION_STATES.FULFILLMENT]: [TRANSACTION_STATES.COMPLETED, TRANSACTION_STATES.DISPUTED],
  [TRANSACTION_STATES.COMPLETED]: [TRANSACTION_STATES.DISPUTED],
  [TRANSACTION_STATES.PAYMENT_FAILED]: [TRANSACTION_STATES.PAYMENT_PENDING, TRANSACTION_STATES.CANCELLED],
  [TRANSACTION_STATES.POLICY_REJECTED]: [],
  [TRANSACTION_STATES.REJECTED]: [],
  [TRANSACTION_STATES.CANCELLED]: [],
};

export function canTransition(currentState, newState) {
  const allowed = ALLOWED_TRANSITIONS[currentState] || [];
  return allowed.includes(newState);
}

export function transitionTransaction(transaction, newState) {
  if (!canTransition(transaction.state, newState)) {
    const allowed = ALLOWED_TRANSITIONS[transaction.state] || [];
    throw new Error(
      `Invalid state transition: Cannot transition from '${transaction.state}' to '${newState}'. Allowed transitions from '${transaction.state}' are: [${allowed.join(", ")}]`
    );
  }

  transaction.state = newState;
  return transaction;
}
