import { TRANSACTION_STATES } from "./transactionStates.js";

/**
 * Single source of truth for allowed transaction state transitions.
 * Maps each state to an array of legal next states (happy path + failure branches).
 */
export const ALLOWED_TRANSITIONS = {
  [TRANSACTION_STATES.DISCOVERED]: [
    TRANSACTION_STATES.QUOTED,
    TRANSACTION_STATES.NEGOTIATING,
    TRANSACTION_STATES.INVENTORY_CHANGED,
  ],
  [TRANSACTION_STATES.QUOTED]: [
    TRANSACTION_STATES.NEGOTIATING,
    TRANSACTION_STATES.AGREED,
    TRANSACTION_STATES.QUOTE_EXPIRED,
    TRANSACTION_STATES.INVENTORY_CHANGED,
  ],
  [TRANSACTION_STATES.NEGOTIATING]: [
    TRANSACTION_STATES.AGREED,
    TRANSACTION_STATES.QUOTE_EXPIRED,
    TRANSACTION_STATES.POLICY_REJECTED,
    TRANSACTION_STATES.INVENTORY_CHANGED,
  ],
  [TRANSACTION_STATES.AGREED]: [
    TRANSACTION_STATES.RESERVED,
    TRANSACTION_STATES.PAYMENT_PENDING,
    TRANSACTION_STATES.HUMAN_APPROVAL_REQUIRED,
    TRANSACTION_STATES.POLICY_REJECTED,
    TRANSACTION_STATES.INVENTORY_CHANGED,
  ],
  [TRANSACTION_STATES.RESERVED]: [
    TRANSACTION_STATES.PAYMENT_PENDING,
    TRANSACTION_STATES.HUMAN_APPROVAL_REQUIRED,
    TRANSACTION_STATES.POLICY_REJECTED,
    TRANSACTION_STATES.INVENTORY_CHANGED,
  ],
  [TRANSACTION_STATES.PAYMENT_PENDING]: [
    TRANSACTION_STATES.PAYMENT_PROCESSING,
    TRANSACTION_STATES.PAYMENT_VERIFICATION,
    TRANSACTION_STATES.PAID,
    TRANSACTION_STATES.PAYMENT_FAILED,
    TRANSACTION_STATES.HUMAN_APPROVAL_REQUIRED,
    TRANSACTION_STATES.POLICY_REJECTED,
  ],
  [TRANSACTION_STATES.PAYMENT_PROCESSING]: [
    TRANSACTION_STATES.PAYMENT_VERIFICATION,
    TRANSACTION_STATES.PAID,
    TRANSACTION_STATES.PAYMENT_FAILED,
  ],
  [TRANSACTION_STATES.PAYMENT_VERIFICATION]: [
    TRANSACTION_STATES.PAID,
    TRANSACTION_STATES.PAYMENT_FAILED,
  ],
  [TRANSACTION_STATES.HUMAN_APPROVAL_REQUIRED]: [
    TRANSACTION_STATES.PAYMENT_PENDING,
    TRANSACTION_STATES.PAYMENT_PROCESSING,
    TRANSACTION_STATES.PAID,
    TRANSACTION_STATES.POLICY_REJECTED,
  ],
  [TRANSACTION_STATES.PAID]: [
    TRANSACTION_STATES.FULFILLMENT,
    TRANSACTION_STATES.COMPLETED,
    TRANSACTION_STATES.REFUND_PENDING,
    TRANSACTION_STATES.DISPUTED,
  ],
  [TRANSACTION_STATES.FULFILLMENT]: [
    TRANSACTION_STATES.COMPLETED,
    TRANSACTION_STATES.REFUND_PENDING,
    TRANSACTION_STATES.DISPUTED,
  ],
  [TRANSACTION_STATES.COMPLETED]: [
    TRANSACTION_STATES.REFUND_PENDING,
    TRANSACTION_STATES.DISPUTED,
  ],
  [TRANSACTION_STATES.PAYMENT_FAILED]: [
    TRANSACTION_STATES.PAYMENT_PENDING,
    TRANSACTION_STATES.PAYMENT_PROCESSING,
    TRANSACTION_STATES.PAYMENT_VERIFICATION,
    TRANSACTION_STATES.PAID,
    TRANSACTION_STATES.REFUND_PENDING,
  ],
  [TRANSACTION_STATES.QUOTE_EXPIRED]: [],
  [TRANSACTION_STATES.INVENTORY_CHANGED]: [
    TRANSACTION_STATES.NEGOTIATING,
  ],
  [TRANSACTION_STATES.POLICY_REJECTED]: [],
  [TRANSACTION_STATES.REFUND_PENDING]: [
    TRANSACTION_STATES.COMPLETED,
    TRANSACTION_STATES.DISPUTED,
  ],
  [TRANSACTION_STATES.DISPUTED]: [
    TRANSACTION_STATES.REFUND_PENDING,
    TRANSACTION_STATES.COMPLETED,
  ],
};

/**
 * Returns true if transition from currentState to newState is allowed.
 */
export function canTransition(currentState, newState) {
  const allowed = ALLOWED_TRANSITIONS[currentState] || [];
  return allowed.includes(newState);
}

/**
 * Returns allowed next states for a given current state.
 */
export function getValidNextStates(currentState) {
  return ALLOWED_TRANSITIONS[currentState] || [];
}
